apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
type: Opaque
data:
  db_name: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
  #  dbUrl: jdbc:postgresql://orderapi-postgresql:5432/orderdb
  db_url:  {{ printf "jdbc:postgresql://%s-postgresql:5432/%s" .Release.Name .Values.postgresql.global.postgresql.auth.database }}
  db_user: {{ .Values.postgresql.global.postgresql.auth.username | quote }}