apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: order-app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "order-api.selectorLabels" . | nindent 4 }}
