apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-prometheus-demo-service-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: order-app-service
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"